### ISSUE TITLE
Hardcoded version

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-lua#13]
I don't fully understand everything that is happening but hardcoded version here seems a bit suspicious:
https://github.com/sublimelsp/LSP-lua/blob/19c22a3d24fe847c51ecd65e7e56a3a59145f8fb/.github/workflows/notify-repository-on-published-release.yml#L20

Is it basically ignored on the other end?

**Comment by rwols** [comment]
Made the appropriate changes to pass along the event payload: https://github.com/sublimelsp/LSP-lua/commit/4abbd6fa2cd8cd8b39f0a851136dcb045ded14a9

See also: https://github.com/sublimelsp/repository/pull/11
