### ISSUE TITLE
lua-language-server can't write/read settings file

### ISSUE THREAD

**Issue by GitSparTV** [sublimelsp/LSP-lua#15]
**Describe the bug**
I'm using `sumneko/lua-language-server` and I encountered a problem when Code Actions doesn't change anything.
Anything settings-file related. In VSCode (since this lsp was made for vscode but allows integrations) the settings are saved into `filedir/.vscode/settings.json`.
log_stderr didn't show any errors in log.
log_debug shows only
```
:: --> lua-ls workspace/executeCommand(125)
:: <<< lua-ls 125
```

**To Reproduce**
Activate this LSP and make undefined global or language specific things.
Example:
```lua
local a = 1LL
```

**Expected behavior**
Settings should be saved and affect lsp output.

**Screenshots**

**Environment:**
- OS: Windows x64
- Sublime Text version: 3.2.2 build 3211
- LSP version: `0.14.3`
- Language servers used: sumneko/lua-language-server

**Comment by rwols** [comment]
Initially everyone thought you could write a *general-purpose* language client (the LSP package), asking the user to set up a connection to a language server with just a few lines of JSON configuration. But experience has shown that you need more than that to unlock the full potential of some language servers. For instance, this lua language server expects the client to handle disaling/enabling some settings for it. The way to do that, as we learned, is to copy the behavior that VSCode has in running a command locally instead of doing an RPC call (as explained in the spec), and write some python client glue code.

**Comment by GitSparTV** [comment]
Is it worth to ask the author of lsp how to make a walkaround for this issue?

**Comment by rwols** [comment]
Which author? There are many parties at play here :)

**Comment by GitSparTV** [comment]
Sumneko

**Comment by rwols** [comment]
You can enable or disable settings "by hand", in a .sublime-project file. I don't know the exact keys to set though.

```js
// yourproject.sublime-project
{
  "folders": [{"path": "."}],
  "settings":
  {
    "LSP": {
      // "Lua", or whatever the name is of your configuration
      "Lua": {
        "settings": {
          "some.key.that.i.dont.know.enabled": false
        }
      }
    }
  }
}
```

**Comment by GitSparTV** [comment]
Alright didn't get it instantly.
Activated globally in client settings of LSP settings.
```json
		"lua-ls": {
			"command": [
				"unpackedsomewhere/sumneko.lua-1.2.1/server/bin/Windows/lua-language-server.exe",
				"-E", "unpackedsomewhere/sumneko.lua-1.2.1/server/main.lua"
			],
			"enabled": true,
			"languageId": "lua",
			"scopes": ["source.lua"],
			"syntaxes": ["Packages/Lua/Lua.sublime-syntax"],
		    "settings": {
		      "Lua.runtime.version": "LuaJIT"
		    }
		}
```
Apparently using this server from .vscode packages folder doesn't work so I had to copy it somewhere else.

Thank you.

**Comment by rwols** [comment]
Yes, for ST3 you need to do all this yourself. This package automates that. Having said that, it still doesn't handle enabling/disabling settings via code actions, so I'll reopen this to remind myself to fix that.

**Comment by rwols** [comment]
This was fixed in https://github.com/sublimelsp/LSP-lua/pull/25
