### ISSUE TITLE
`/Package Storage` directory needs to have been pre-created for automatic setup to work

### ISSUE THREAD

**Issue by RheingoldRiver** [sublimelsp/LSP-lua#16]
https://github.com/sublimelsp/LSP-lua/blob/a522abfe3f54ffc8888c10fe2b08372580b7b0b7/plugin.py#L78

Pretty sure this line isn't executing if `/Package Storage` doesn't already exist; in Sublimetext 4 build 4105 on Windows, I couldn't get the setup to work until I manually created this folder myself.

(I mentioned this issue in Discord already, but making a ticket here too for proper documentation of the issue.)

**Comment by rwols** [comment]
Fixed in 9484edcf5dd56e740b6799b9668df9bdbdfe5d2a
