### ISSUE TITLE
startup error: invalid cross-device link

### ISSUE THREAD

**Issue by basaran** [sublimelsp/LSP-lua#19]
Hello,

While trying to enable, LSP-lua, this comes up:

![image](https://user-images.githubusercontent.com/30809170/123493762-744a7680-d5eb-11eb-9fab-8369d1c97a5f.png)

If you could provide assistance, I will surely appreciate it. Thank you.

**Comment by basaran** [comment]
I figured it out, it was the shutil vs os.rename situation. I think the git repo is newer, so I will try that instead of the sublime package. If you could please update the package repository, it will make non python people's life more enjoyable :)

```
shutil.move(os.path.join(tmp, "extension", "server"), cls.basedir())
```

I can send a PR if you like.

**Comment by rwols** [comment]
Yes, please send a PR.

**Comment by rwols** [comment]
Actually, v1.0.1 is at the tip of the master branch. And packagecontrol.io reports 1.0.1 https://packagecontrol.io/packages/LSP-lua

**Comment by rwols** [comment]
Ah I understand your problem now. So the temporary directory is created on a different drive than the cache destination. And os.rename doesn't work with different drives, but shutil.move does https://docs.python.org/3/library/shutil.html#shutil.move

**Comment by rwols** [comment]
@basaran how about those pull requests?

**Comment by rwols** [comment]
I used shutil.move in b593376. Server will be upgraded in #21.

**Comment by basaran** [comment]
oh shoot :) I forgot, I'm so sorry, I have been working on this awesomewm config and completely zones out from this. Let me review the changes in a sec.
