### ISSUE TITLE
Mark '...' as defined global not working.

### ISSUE THREAD

**Issue by rogeriodec** [sublimelsp/LSP-lua#20]
I'm using Roblox-Lua and there are some internal global variables that don't need to be declared, such as "workspace", "Vector3", etc.
LSP-Lua is showing this warning:

![image](https://user-images.githubusercontent.com/11199752/124400210-23c3cf00-dcf7-11eb-8aa7-5da858ce1865.png)

If I choose `Mark 'workspace' as defined global, it changes nothing:
![image](https://user-images.githubusercontent.com/11199752/124400228-481fab80-dcf7-11eb-9fdc-6706b6529300.png)

What's wrong?

**Comment by rchl** [comment]
It's supposed to update your project settings with something like:

![Screenshot 2021-07-04 at 23 53 48](https://user-images.githubusercontent.com/153197/124400491-16243e80-dd23-11eb-91b7-841d49491a1b.png)

Make sure that you have opened a folder instead of a single file.
And ideally save the workspace as a project so that your settings are preserved.

(Note that there are warnings in project settings when using `LSP-json` but that hopefully doesn't affect the behavior)

**Comment by rogeriodec** [comment]
Thanks. In fact, I had to create a project for it. I've never actually used projects before, but that's okay.

![image](https://user-images.githubusercontent.com/11199752/124401118-12ca8c00-dcfe-11eb-92dc-fe2f9bbbc1a5.png)

However, there is an issue:
If I Mark a variable as defined global, ALL  other variables that appear underlined with the same problem are no longer charged.

Before:

![image](https://user-images.githubusercontent.com/11199752/124401296-009d1d80-dcff-11eb-96cc-360875353ead.png)

After:

![image](https://user-images.githubusercontent.com/11199752/124401298-07c42b80-dcff-11eb-9635-bf7c51d446cd.png)



To get the correct result, I have to close the file and open it again:

![image](https://user-images.githubusercontent.com/11199752/124401312-1a3e6500-dcff-11eb-91c8-0a63143db665.png)

**Comment by rwols** [comment]
What you probably want is to use the `Lua.workspace.library` setting to point to a Roblox interface. I don't know exactly how that works though. I believe @zainthemaynnn got that working.

https://github.com/sublimelsp/LSP-lua/blob/3dbb0e5ae41f96e36bc8f0be5b11202d08b96e62/LSP-lua.sublime-settings#L162-L166

**Comment by rogeriodec** [comment]
Actually @rchl [solved](https://github.com/sublimelsp/LSP-lua/issues/20#issuecomment-873669818) the original problem. 
My last post is to inform another behavior.
