### ISSUE TITLE
Lua.workspace.checkThirdParty is not allowed

### ISSUE THREAD

**Issue by lua-rocks** [sublimelsp/LSP-lua#32]
![screenshot](https://user-images.githubusercontent.com/82697845/150608943-edffec7e-c27e-4d38-b72d-574e70deedbb.png)

**Comment by rchl** [comment]
What is the name of that file?

**Comment by lua-rocks** [comment]
It opens when you type "lsp-lua" in command menu:

![screenshot](https://user-images.githubusercontent.com/82697845/150767473-8b93451d-3865-45a2-863f-68ef25f2d8fd.png)

Its name is `LSP-lua.sublime-settings`.

**Comment by lua-rocks** [comment]
This option tries to set automatically to false when server detects a 3d-party environment, such as love2d.

**Comment by rwols** [comment]
Fixed in https://github.com/sublimelsp/LSP-lua/commit/d03bb9fb0bdd67faba1d8b3ab5edaf5938ac26f5
